/***************************************************************************
 *
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 *
 *  				     Copyright (C) Themify
 *
 *	----------------------------------------------------------------------
 *
 ***************************************************************************/

(function($){

	$(document).ready(function(){

		// Layout Field
		$( '.preview-icon' ).click( function ( e ) {
			e.preventDefault();
			$( this ).parent().parent().find( '.selected' ).removeClass( 'selected' );
			$( this ).addClass( 'selected' );
			$( this ).parent().parent().find( '.val' ).val( $( this ).find( 'img' ).attr( 'alt' ) );
		});

	});
	
})(jQuery);

